# Generated by Django 3.1.1 on 2020-09-29 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='notifier',
        ),
        migrations.RemoveField(
            model_name='post',
            name='notifier',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='notifier',
        ),
        migrations.AddField(
            model_name='notifier',
            name='comment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifier', to='posts.comment'),
        ),
        migrations.AddField(
            model_name='notifier',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifier', to='posts.post'),
        ),
        migrations.AddField(
            model_name='notifier',
            name='reply',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifier', to='posts.reply'),
        ),
        migrations.AlterField(
            model_name='notifier',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='posts.comment'),
        ),
    ]
